from enum import Enum

class FindingStatus(str, Enum):
    DISCOVERED = "DISCOVERED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    ISSUE_CREATING = "ISSUE_CREATING"
    ISSUE_CREATED = "ISSUE_CREATED"

class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    NEEDS_MORE_CONTEXT = "NEEDS_MORE_CONTEXT"
    FAILED = "FAILED"

class EvidenceStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    UNKNOWN = "UNKNOWN"
